export const artists = [
    {
        slug: "frankywright",
        name: "Frankywright",
        bio: "Frankywright is a visionary artist known for his eclectic sound and powerful lyrics.",
        image: "/images/artists/frankywright.jpg",
        youtube: "https://youtube.com",
        instagram: "https://instagram.com",
        twitter: "https://twitter.com",
        color: "from-purple-500 to-blue-500",
        songs: [],
    },
    {
        slug: "beverly-hills",
        name: "Beverly Hills",
        bio: "Beverly Hills brings the glamour and grit of the city to her music.",
        image: "/images/artists/beverly-hills.jpg",
        youtube: "https://youtube.com",
        instagram: "https://instagram.com",
        twitter: "https://twitter.com",
        color: "from-pink-500 to-rose-500",
        songs: [],
    },
    {
        slug: "mc-da-hills",
        name: "MC Da-Hills",
        bio: "MC Da-Hills is a lyrical genius with a flow that never quits.",
        image: "/images/artists/mc-da-hills.jpg",
        youtube: "https://youtube.com",
        instagram: "https://instagram.com",
        twitter: "https://twitter.com",
        color: "from-green-500 to-emerald-500",
        songs: [],
    },
    {
        slug: "obi-golden",
        name: "Obi Golden",
        bio: "Obi Golden shines bright with afrobeat rhythms and soulful melodies.",
        image: "/images/artists/obi-golden.jpg",
        youtube: "https://youtube.com",
        instagram: "https://instagram.com",
        twitter: "https://twitter.com",
        color: "from-yellow-500 to-orange-500",
        songs: [],
    },
    {
        slug: "queen-idia",
        name: "Queen - Idia",
        bio: "The Queen of the scene, bringing royal vibes to every track.",
        image: "/images/artists/queen-idia.jpg",
        youtube: "https://youtube.com",
        instagram: "https://instagram.com",
        twitter: "https://twitter.com",
        color: "from-red-500 to-red-800",
        songs: [],
    },
    {
        slug: "jojo-the-creator",
        name: "Jojo The Creator",
        bio: "Creating new worlds with sound.",
        image: "/images/artists/jojo.jpg",
        youtube: "https://youtube.com",
        instagram: "https://instagram.com",
        twitter: "https://twitter.com",
        color: "from-indigo-500 to-purple-500",
        songs: [],
    },
    {
        slug: "franklin-ugwu",
        name: "Franklin Ugwu",
        bio: "The mastermind behind the music.",
        image: "/images/artists/franklin.jpg",
        youtube: "https://youtube.com",
        instagram: "https://instagram.com",
        twitter: "https://twitter.com",
        color: "from-cyan-500 to-blue-500",
        songs: [],
    },
];
